### ISSUE TITLE
UI is missing buttons etc.

### ISSUE THREAD

**Issue by thomas2net** [jjdejong/phpip#40]
I installed, logged in. Looked quite empty
Tried: php artisan db:seed --class=SampleSeeder
Seeding: ActorSampleSeeder
Seeded:  ActorSampleSeeder (0.02 seconds)
(...)
(?, EXA, ?, 2017-07-28, 67, 10, ?))

  at /var/www/html/phpip/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='")
      /var/www/html/phpip/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123

  2   PDOException::("SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='")
      /var/www/html/phpip/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121

  Please use the argument -v to see more details.
![image](https://user-images.githubusercontent.com/16047553/76806085-cabde800-67e0-11ea-9e23-9d32a8566ef0.png)

Looks like the UI is missing some buttons?

**Comment by papoteur-mga** [comment]
Collations are indication on how to sort data in columns in the database. This has nothing to do with the UX.
The problem here is that some columns in the database which refers to each others have different collation. We have to find how to add some directives.
Which database manager do you use?

**Comment by jjdejong** [comment]
The UI is not really missing buttons, there aren't that many, and some become visible when hovering the mouse over items, plus you have some functionality in the menu. All you need is available.

Otherwise you've run into the so-called "[character-set hell](https://medium.com/@manish_demblani/breaking-out-from-the-mysql-character-set-hell-24c6a306e1e5)" that MySQL 8 has introduced (I've had the problem a few times with v8 and had no problem with 5.7). 

phpIP does not use new features of v8 yet, so you could downgrade to v5.7.

Anyway, try re-creating the `phpip` schema by explicitly specifying the utf8mb4_unicode_ci collation. Somehow v8 defaults to utf8mb4_0900_ai_ci in some cases.

**Comment by jjdejong** [comment]
Plus, if you don't use the "recommended" specifications, i.e. Ubuntu Bionic, you will run into issues we've not experienced. If you're not comfortable with solving the new issues yourself and contributing your solutions, you should really stick to the recommended specs!
