### ISSUE TITLE
2019_12_06_002_alter_task_table

### ISSUE THREAD

**Issue by alexandreIP** [jjdejong/phpip#56]
desolé, j'ai une erreur sur une migration précédente, c'est peut être en rapport ?
voici ma version de maria db: 10.3.22-MariaDB-0+deb10u1

Migrating: 2019_12_06_002_alter_task_table

   Illuminate\Database\QueryException 

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '`task_before_update` BEFORE UPDATE ON `task` FOR EACH ROW 
BEGIN
  IF NEW.done_d' at line 1 (SQL: CREATE `task_before_update` BEFORE UPDATE ON `task` FOR EACH ROW 
BEGIN
  IF NEW.done_date IS NOT NULL AND OLD.done_date IS NULL AND OLD.done = 0 THEN
    SET NEW.done = 1;
  END IF;
  IF NEW.done_date IS NULL AND OLD.done_date IS NOT NULL AND OLD.done = 1 THEN
    SET NEW.done = 0;
  END IF;
  IF NEW.done = 1 AND OLD.done = 0 AND NEW.done_date IS NULL THEN
    SET NEW.done_date = Least(OLD.due_date, Now());
  END IF;
  IF NEW.done = 0 AND OLD.done = 1 AND OLD.done_date IS NOT NULL THEN
    SET NEW.done_date = NULL, NEW.step = 0, NEW.invoice_step = 0, NEW.grace_period = 0;
  END IF;
END)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
    667|         // If an exception occurs when attempting to run a query, we'll format the error
    668|         // message to include the bindings with SQL, which will make this exception a
    669|         // lot more helpful to the developer instead of just the database's errors.
    670|         catch (Exception $e) {
  > 671|             throw new QueryException(
    672|                 $query, $this->prepareBindings($bindings), $e
    673|             );
    674|         }
    675| 

      +9 vendor frames 
  10  database/migrations/2019_12_06_002_alter_task_table.php:30
      Illuminate\Support\Facades\Facade::__callStatic("unprepared")

      +22 vendor frames 
  33  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by vertbois** [comment]
Pour cette erreur,

J’ai créé le déclencheur manuellement avec navicat (j’ai la même version de mariadb). J’ai ensuite complété la table migration pour que les migrations futures soient faites.

Cordialement,

Samuel GRYNWALD
Vertbois Informatique

De : alexandreIP <notifications@github.com>
Envoyé : dimanche 14 juin 2020 13:51
À : jjdejong/phpip <phpip@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [jjdejong/phpip] 2019_12_06_002_alter_task_table (#56)


desolé, j'ai une erreur sur une migration précédente, c'est peut être en rapport ?
voici ma version de maria db: 10.3.22-MariaDB-0+deb10u1

Migrating: 2019_12_06_002_alter_task_table

Illuminate\Database\QueryException

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'task_before_update BEFORE UPDATE ON task FOR EACH ROW
BEGIN
IF NEW.done_d' at line 1 (SQL: CREATE task_before_update BEFORE UPDATE ON task FOR EACH ROW
BEGIN
IF NEW.done_date IS NOT NULL AND OLD.done_date IS NULL AND OLD.done = 0 THEN
SET NEW.done = 1;
END IF;
IF NEW.done_date IS NULL AND OLD.done_date IS NOT NULL AND OLD.done = 1 THEN
SET NEW.done = 0;
END IF;
IF NEW.done = 1 AND OLD.done = 0 AND NEW.done_date IS NULL THEN
SET NEW.done_date = Least(OLD.due_date, Now());
END IF;
IF NEW.done = 0 AND OLD.done = 1 AND OLD.done_date IS NOT NULL THEN
SET NEW.done_date = NULL, NEW.step = 0, NEW.invoice_step = 0, NEW.grace_period = 0;
END IF;
END)

at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
667| // If an exception occurs when attempting to run a query, we'll format the error
668| // message to include the bindings with SQL, which will make this exception a
669| // lot more helpful to the developer instead of just the database's errors.
670| catch (Exception $e) {

671| throw new QueryException(
672| $query, $this->prepareBindings($bindings), $e
673| );
674| }
675|

  +9 vendor frames



10 database/migrations/2019_12_06_002_alter_task_table.php:30
Illuminate\Support\Facades\Facade::__callStatic("unprepared")

  +22 vendor frames



33 artisan:37
Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by alexandreIP** [comment]
merci... 
je ne suis pas sur de comprendre les tests faits et je n'ai pas navicat.
Si je comprends bien il faut que:
1. je trouve dans quelle condition (If, End) 
2. j'applique ensuite une requête SQL (je suis sur phpmyadmin).

**Comment by vertbois** [comment]
Voici la commande SQL pour créer le déclencheur :

CREATE TRIGGER `task_before_update` BEFORE UPDATE ON `task` FOR EACH ROW BEGIN
  IF NEW.done_date IS NOT NULL AND OLD.done_date IS NULL AND OLD.done = 0 THEN
    SET NEW.done = 1;
  END IF;
  IF NEW.done_date IS NULL AND OLD.done_date IS NOT NULL AND OLD.done = 1 THEN
    SET NEW.done = 0;
  END IF;
  IF NEW.done = 1 AND OLD.done = 0 AND NEW.done_date IS NULL THEN
    SET NEW.done_date = Least(OLD.due_date, Now());
  END IF;
  IF NEW.done = 0 AND OLD.done = 1 AND OLD.done_date IS NOT NULL THEN
    SET NEW.done_date = NULL, NEW.step = 0, NEW.invoice_step = 0, NEW.grace_period = 0;
  END IF;
END;

Cordialement,

Samuel GRYNWALD
Vertbois Informatique

PS : pour modifier les collations, je pense qu’il est plus rapide de sauvegarder la base dans un fichier sql que l’on retravaille (remplacer utf8 par utf8mb4 dans Ms Word par exemple) puis de le réinjecter dans une nouvelle base.
De : alexandreIP <notifications@github.com>
Envoyé : dimanche 14 juin 2020 16:38
À : jjdejong/phpip <phpip@noreply.github.com>
Cc : Vertbois Informatique <samuel.grynwald@vertbois-informatique.fr>; Comment <comment@noreply.github.com>
Objet : Re: [jjdejong/phpip] 2019_12_06_002_alter_task_table (#56)


merci...
je ne suis pas sur de comprendre les tests faits et je n'ai pas navicat.
Si je comprends bien il faut que:

  1.  je trouve dans quelle condition (If, End)
  2.  j'applique ensuite une requête SQL (je suis sur phpmyadmin).

**Comment by papoteur-mga** [comment]
Bonjour,
Il manquait le mot clé TRIGGER après CREATE.
J'ai fait la modification.

**Comment by alexandreIP** [comment]
Merci !
