### ISSUE TITLE
php artisan migrate:fresh

### ISSUE THREAD

**Issue by alexandreIP** [jjdejong/phpip#57]
Bonjour à tous,

lorsqu'on lance cette commande : php artisan migrate:fresh 

On obtient l'erreur suivante...

Alexandre

Migrating: 2018_12_08_002558_create_views_and_functions

   Illuminate\Database\QueryException 

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'task_list' already exists (SQL: CREATE
          VIEW `task_list` AS select `task`.`ID` AS `id`,
          `task`.`code` AS `code`,
          `event_name`.`name` AS `name`,
          `task`.`detail` AS `detail`,
          `task`.`due_date` AS `due_date`,
          `task`.`done` AS `done`,
          `task`.`done_date` AS `done_date`,
          `event`.`matter_ID` AS `matter_id`,
          `task`.`cost` AS `cost`,
          `task`.`fee` AS `fee`,
          `task`.`trigger_ID` AS `trigger_id`,
          `matter`.`category_code` AS `category`,
          `matter`.`caseref` AS `caseref`,
          `matter`.`country` AS `country`,
          `matter`.`origin` AS `origin`,
          `matter`.`type_code` AS `type_code`,
          `matter`.`idx` AS `idx`,
          ifnull(`task`.`assigned_to`,`matter`.`responsible`) AS `responsible`,
          `actor`.`login` AS `delegate`,
          `task`.`rule_used` AS `rule_used`,
          `matter`.`dead` AS `dead`
          from (((((`matter`
          left join `matter_actor_lnk` on(((ifnull(`matter`.`container_ID`,`matter`.`ID`) = `matter_actor_lnk`.`matter_ID`) and (`matter_actor_lnk`.`role` = 'DEL'))))
          left join `actor` on((`actor`.`ID` = `matter_actor_lnk`.`actor_ID`)))
          join `event` on((`matter`.`ID` = `event`.`matter_ID`)))
          join `task` on((`task`.`trigger_ID` = `event`.`ID`)))
          join `event_name` on((`task`.`code` = `event_name`.`code`))))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
    667|         // If an exception occurs when attempting to run a query, we'll format the error
    668|         // message to include the bindings with SQL, which will make this exception a
    669|         // lot more helpful to the developer instead of just the database's errors.
    670|         catch (Exception $e) {
  > 671|             throw new QueryException(
    672|                 $query, $this->prepareBindings($bindings), $e
    673|             );
    674|         }
    675| 

      +9 vendor frames 
  10  database/migrations/2018_12_08_002558_create_views_and_functions.php:14
      Illuminate\Support\Facades\Facade::__callStatic("statement")

      +34 vendor frames 
  45  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by vertbois** [comment]
En lisant la doc de Laravel, la commande :fresh supprime toutes les tables (et pas le reste donc les vues) et applique toutes les migrations ; la commande :refresh supprime toutes les migrations puis les relances (ayant pour conséquence la recréation d’une base vierge).
Le message d’erreur indique qu’une vue existe déjà.

Cordialement,

Samuel GRYNWALD
Vertbois Informatique

De : alexandreIP <notifications@github.com>
Envoyé : dimanche 14 juin 2020 18:24
À : jjdejong/phpip <phpip@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [jjdejong/phpip] php artisan migrate:fresh (#57)


Bonjour à tous,

lorsqu'on lance cette commande : php artisan migrate:fresh

On obtient l'erreur suivante...

Alexandre

Migrating: 2018_12_08_002558_create_views_and_functions

Illuminate\Database\QueryException

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'task_list' already exists (SQL: CREATE
VIEW task_list AS select task.ID AS id,
task.code AS code,
event_name.name AS name,
task.detail AS detail,
task.due_date AS due_date,
task.done AS done,
task.done_date AS done_date,
event.matter_ID AS matter_id,
task.cost AS cost,
task.fee AS fee,
task.trigger_ID AS trigger_id,
matter.category_code AS category,
matter.caseref AS caseref,
matter.country AS country,
matter.origin AS origin,
matter.type_code AS type_code,
matter.idx AS idx,
ifnull(task.assigned_to,matter.responsible) AS responsible,
actor.login AS delegate,
task.rule_used AS rule_used,
matter.dead AS dead
from (((((matter
left join matter_actor_lnk on(((ifnull(matter.container_ID,matter.ID) = matter_actor_lnk.matter_ID) and (matter_actor_lnk.role = 'DEL'))))
left join actor on((actor.ID = matter_actor_lnk.actor_ID)))
join event on((matter.ID = event.matter_ID)))
join task on((task.trigger_ID = event.ID)))
join event_name on((task.code = event_name.code))))

at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
667| // If an exception occurs when attempting to run a query, we'll format the error
668| // message to include the bindings with SQL, which will make this exception a
669| // lot more helpful to the developer instead of just the database's errors.
670| catch (Exception $e) {

671| throw new QueryException(
672| $query, $this->prepareBindings($bindings), $e
673| );
674| }
675|

  +9 vendor frames



10 database/migrations/2018_12_08_002558_create_views_and_functions.php:14
Illuminate\Support\Facades\Facade::__callStatic("statement")

  +34 vendor frames



45 artisan:37
Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
