### ISSUE TITLE
Base date for annuity in Poland should be the filing date

### ISSUE THREAD

**Issue by papoteur-mga** [jjdejong/phpip#66]
Today, it is the grant date.
Source: https://www.wipo.int/export/sites/www/pct/guide/fr/gdvol2/annexes/pl.pdf
Foot note 1 of page 6.

**Comment by jjdejong** [comment]
Not clear what the anniversary date is, though. Our renewal subcontractor uses the filing date as anniversary. And this is for direct national phases in Poland from the PCT, which most of us won't use, because we use the European route, which is ruled by [Art. 141(2) EPC](https://www.epo.org/law-practice/legal-texts/html/epc/2016/e/ar141.html).
